name: pull-request-lint
on:
  pull_request_target:
    types:
      - labeled
      - opened
      - synchronize
      - reopened
      - ready_for_review
      - edited
  merge_group: {}
jobs:
  validate:
    name: Validate PR title
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write
    steps:
      - name: Skip on merge queue
        if: github.event_name == 'merge_group'
        run: echo "Skipping lint in merge queue context"
      - uses: amannn/action-semantic-pull-request@v5.5.3
        if: github.event_name == 'pull_request_target'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          types: |-
            chore
            ci
            feat
            fix
            merge queue
          requireScope: false
